//! 直接复用现有示例的 OCR、窗口输入和气泡验证实现。
#[path = "../wechat_demo/bubbles.rs"]
pub mod bubbles;
#[path = "../wechat_demo/capture.rs"]
pub mod capture;
#[path = "../wechat_demo/conversation.rs"]
pub mod conversation;
#[path = "../wechat_demo/conversation_state.rs"]
pub mod conversation_state;
#[path = "../wechat_demo/desktop.rs"]
pub mod desktop;
#[path = "../wechat_demo/editor.rs"]
pub mod editor;
#[path = "../wechat_demo/frame.rs"]
pub mod frame;
#[path = "../wechat_demo/incremental.rs"]
pub mod incremental;
#[path = "../wechat_demo/layout.rs"]
pub mod layout;
#[path = "../wechat_demo/message_tracking.rs"]
pub mod message_tracking;
#[path = "../wechat_demo/observation.rs"]
pub mod observation;
#[path = "../wechat_demo/pixel_motion.rs"]
pub mod pixel_motion;
#[path = "../wechat_demo/recovery.rs"]
pub mod recovery;
#[path = "../wechat_demo/scroll_motion.rs"]
pub mod scroll_motion;
#[path = "../wechat_demo/send_trace.rs"]
pub mod send_trace;
#[path = "../wechat_demo/send_verification.rs"]
pub mod send_verification;
#[path = "../wechat_demo/snapshot.rs"]
pub mod snapshot;
#[path = "../wechat_demo/spatial.rs"]
pub mod spatial;
#[path = "../wechat_demo/text.rs"]
pub mod text;
