/**
 * 新工作区直接打开一个可编辑的完整示例；此模块只负责把示例公开为默认文档契约。
 */
export {
  WECHAT_WORKFLOW_EDGES as DEFAULT_EDGES,
  WECHAT_WORKFLOW_INPUTS as DEFAULT_WORKFLOW_INPUTS,
  WECHAT_WORKFLOW_NAME as DEFAULT_WORKFLOW_NAME,
  WECHAT_WORKFLOW_NODES as DEFAULT_NODES,
  WECHAT_WORKFLOW_PERMISSIONS as DEFAULT_WORKFLOW_PERMISSIONS,
  WECHAT_WORKFLOW_VARIABLES as DEFAULT_WORKFLOW_VARIABLES,
  WECHAT_RUN_INPUT_VALUES as DEFAULT_RUN_INPUT_VALUES,
  WECHAT_SELECTED_NODE_ID as DEFAULT_SELECTED_NODE_ID,
} from '../examples/wechat/template';
